### ISSUE TITLE
[Bug] ComfyUI hangs on startup + IndexTTS-2 crashes on Python 3.13

### ISSUE THREAD

**Issue by hendrikreimers** [diodiogod/TTS-Audio-Suite#271]
**First of all, FYI:**
I wrote this ticket and solution with the help of ClaudeAI. I hope it still helps you to fix it. The current patches working for me.
Fresh installed comfyui portable latest version.

## Environment
- **ComfyUI:** v0.16.4 (Windows Portable)
- **TTS Audio Suite:** v4.22.5
- **Python:** 3.13.11
- **PyTorch:** 2.10.0+cu130
- **Numba:** 0.64.0
- **Librosa:** 0.11.0
- **GPU:** NVIDIA GeForce RTX 5070 Ti (16 GB)
- **NVIDIA Driver:** 595.x (r590 branch)
- **OS:** Windows 10/11

---

### Description

After installing TTS Audio Suite, ComfyUI hangs indefinitely on startup. The console output stops after the FFmpeg warning and never reaches the server start. Without the `tts_audio_suite` folder in `custom_nodes`, ComfyUI starts instantly.

### Root Cause

The hang occurs in `nodes.py` at line ~242 when `nodes/audio/recorder_node.py` is loaded via `load_node_module()`. That module imports `sounddevice`, which triggers PortAudio's `Pa_Initialize()` at import time. This function enumerates all audio devices across all Windows audio APIs (MME, DirectSound, WASAPI, ASIO). On my system, this enumeration never returns — likely because PortAudio hangs while querying the WASAPI exclusive-mode capabilities of the NVIDIA HD Audio driver (installed with the RTX 5070 Ti GPU driver).

This is a known class of issue with PortAudio on Windows when certain audio drivers (NVIDIA HD Audio, virtual audio devices like Voicemeeter/VB-Cable) don't respond to capability queries within a reasonable time. PortAudio has no timeout for these queries, so it blocks forever.

### How I Diagnosed It

1. Renamed `custom_nodes/tts_audio_suite` → starts fine ✅
2. Tested `HF_HUB_OFFLINE=1` / `TRANSFORMERS_OFFLINE=1` → still hangs ❌
3. Tested `NUMBA_DISABLE_JIT=1` → still hangs ❌
4. Wrote a test script loading each engine module individually → all engines load fine ✅
5. Wrote a comprehensive test script loading **every** node module from `nodes.py` individually → **`recorder_node.py` is the one that hangs** ❌
6. Disabled the recorder_node load in `nodes.py` → ComfyUI starts fine with all TTS functionality working ✅

### Temporary Workaround

In `nodes.py` around line 241, I replaced:

```python
try:
    audio_recorder_module = load_node_module("chatterbox_audio_recorder_node", "audio/recorder_node.py")
    ChatterBoxVoiceCapture = audio_recorder_module.ChatterBoxVoiceCapture
    VOICE_CAPTURE_AVAILABLE = True
except Exception as e:
    print(f"❌ Voice Capture failed: {e}")
    VOICE_CAPTURE_AVAILABLE = False
```

with:

```python
# DISABLED: sounddevice import hangs on PortAudio device enumeration
VOICE_CAPTURE_AVAILABLE = False
```

### Suggested Fix

The `sounddevice` import in `recorder_node.py` should not happen at ComfyUI startup. Options:

1. **Lazy import:** Don't import `sounddevice` at module level in `recorder_node.py`. Instead, import it inside the node's `FUNCTION` method on first use. This way PortAudio is only initialized when someone actually uses the Voice Capture node.

2. **Timeout wrapper:** Import `sounddevice` in a separate thread with a timeout (e.g. 10 seconds). If it doesn't complete, set `VOICE_CAPTURE_AVAILABLE = False` and print a warning instead of blocking the entire startup.

3. **Deferred registration:** Similar to how transformers version checking is deferred, defer the recorder_node load to first use rather than plugin initialization.

Option 1 (lazy import) would be the simplest and most robust solution, since it avoids the PortAudio initialization entirely for users who don't need voice recording.

### Startup Log (truncated at hang point)

```
ComfyUI frontend version: 1.39.19
[Prompt Server] web root: C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\comfyui_frontend_package\static
[START] ComfyUI-Manager
[ComfyUI-Manager] network_mode: public
   🔧 torchaudio.save/load globally patched (scipy for WAV files, no TorchCodec)
   🔇 Suppressed torchaudio 2.9 migration warnings
ℹ️ Critical package versions: NumPy 2.2.6, Librosa 0.11.0, Numba 0.64.0, PyTorch 2.10.0+cu130,
   TorchAudio 2.10.0+cu130, Transformers 4.57.3, Accelerate 1.13.0, SoundFile 0.13.1
⚠️ FFmpeg not found - using fallback audio processing (reduced quality)
💡 Install FFmpeg for optimal performance: https://ffmpeg.org/download.html
FETCH DATA from: ...\custom-node-list.json [DONE]
<-- hangs here indefinitely, never reaches "Starting server" -->
```

---

### Description

After fixing the startup hang (Bug 1 above), IndexTTS-2 fails at inference time with:

```
❌ IndexTTS-2 processor error: 'function' object has no attribute 'get_call_template'
```

The crash occurs when `infer_v2.py` calls `librosa.load()`, which lazy-imports `librosa.core.audio`. That module uses `@guvectorize` (line 1154), which Numba 0.64.0 cannot compile on Python 3.13.

**Important:** `NUMBA_DISABLE_JIT=1` does **NOT** fix this. That env var only disables `@jit`/`@njit` decorators, but `@guvectorize` is always compiled regardless.

### Affected Code

`engines/index_tts/indextts/infer_v2.py`, function `_load_and_cut_audio()` — two `librosa.load()` calls (lines ~475 and ~481).

Other engines using `librosa.load()` anywhere in their code will have the same issue on Python 3.13.

### Error Traceback (shortened)

```
File "...\infer_v2.py", line 475, in _load_and_cut_audio
    audio, sr = librosa.load(audio_path)
File "...\librosa\core\audio.py", line 1154, in <module>
    @guvectorize(
File "...\numba\np\ufunc\decorators.py", line 203, in wrap
    guvec.add(fty)
...
File "...\numba\core\types\functions.py", line 541, in get_call_type
    self.dispatcher.get_call_template(args, kws)
AttributeError: 'function' object has no attribute 'get_call_template'
```

### Temporary Workaround

Replace both `librosa.load()` calls in `_load_and_cut_audio()` with `soundfile.read()`:

```python
# Instead of: audio, sr = librosa.load(audio_path)
import soundfile as sf
audio, sr = sf.read(audio_path, dtype='float32')
if len(audio.shape) > 1:
    audio = audio.mean(axis=1)

# Instead of: audio, _ = librosa.load(audio_path, sr=sr)
import soundfile as sf
audio, _sr = sf.read(audio_path, dtype='float32')
if len(audio.shape) > 1:
    audio = audio.mean(axis=1)
if _sr != sr:
    import torchaudio
    audio_t = torch.from_numpy(audio).unsqueeze(0)
    audio_t = torchaudio.functional.resample(audio_t, _sr, sr)
    audio = audio_t.squeeze(0).numpy()
```

**Note:** Do NOT use `import torch` inside the replacement block — if `torch` is already imported at module level, a local `import torch` inside an `if` branch causes Python to shadow the global with an unbound local, resulting in `UnboundLocalError`.

### Suggested Fix

On Python 3.13, **all** `librosa.load()` calls across the entire codebase should be replaced with `soundfile` or `torchaudio` alternatives. The `@guvectorize` decorator is fundamentally broken on Python 3.13 with Numba 0.64.0, and `NUMBA_DISABLE_JIT` cannot help because it does not affect `@guvectorize`.

A project-wide search for `librosa.load` and `librosa.resample` would catch all affected locations. Both `soundfile` and `torchaudio` are already listed as dependencies, so no new packages are needed.
