### ISSUE TITLE
[Bug]AttributeError: 'Qwen3TTSModel' object has no attribute 'is_dynamic' with ComfyUI > 0.11.0

### ISSUE THREAD

**Issue by wasd-tech** [diodiogod/TTS-Audio-Suite#247]
**Describe the bug**
`AttributeError: 'Qwen3TTSModel' object has no attribute 'is_dynamic'` if I use a ComfyUI version  > 0.11.0

**Init log**
```
[ComfyUI-Manager] Using uv as Python module for pip operations.
Using Python 3.12.12 environment at: /home/USER/.conda/envs/comfyui
[DONE] Security scan
** ComfyUI startup time: 2026-02-03 20:06:16.769
** Platform: Linux
** Python version: 3.12.12 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 20:16:04) [GCC 11.2.0]
** Python executable: /home/USER/.conda/envs/comfyui/bin/python
** ComfyUI Path: /home/USER/ROCm/Almalinux/ComfyUI
** ComfyUI Base Folder Path: /home/USER/ROCm/Almalinux/ComfyUI
** User directory: /home/USER/ROCm/Almalinux/ComfyUI/user
** ComfyUI-Manager config path: /home/USER/ROCm/Almalinux/ComfyUI/user/__manager/config.ini
** Log path: /home/USER/ROCm/Almalinux/ComfyUI/user/comfyui.log
Using Python 3.12.12 environment at: /home/USER/.conda/envs/comfyui
Using Python 3.12.12 environment at: /home/USER/.conda/envs/comfyui
[PRE] ComfyUI-Manager

Prestartup times for custom nodes:
   0.0 seconds: /home/USER/ROCm/Almalinux/ComfyUI/custom_nodes/rgthree-comfy
   0.0 seconds: /home/USER/ROCm/Almalinux/ComfyUI/custom_nodes/comfyui-easy-use
   0.0 seconds: /home/USER/ROCm/Almalinux/ComfyUI/custom_nodes/comfyui_dados_nodes

Checkpoint files will always be loaded safely.
Found comfy_kitchen backend eager: {'available': True, 'disabled': False, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8', 'scaled_mm_nvfp4']}
Found comfy_kitchen backend triton: {'available': True, 'disabled': True, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8']}
Found comfy_kitchen backend cuda: {'available': True, 'disabled': True, 'unavailable_reason': None, 'capabilities': ['apply_rope', 'apply_rope1', 'dequantize_nvfp4', 'dequantize_per_tensor_fp8', 'quantize_nvfp4', 'quantize_per_tensor_fp8']}
Total VRAM 16304 MB, total RAM 31689 MB
pytorch version: 2.10.0.dev20260111+rocm7.2.0.gitdea53f5b
Set: torch.backends.cudnn.enabled = False for better AMD performance.
AMD arch: gfx1201
ROCm version: (7, 2)
Set vram state to: NORMAL_VRAM
Disabling smart memory management
Device: cuda:0 AMD Radeon Graphics : native
Using async weight offloading with 2 streams
Enabled pinned memory 30104.0
Using pytorch attention
Python version: 3.12.12 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 20:16:04) [GCC 11.2.0]
ComfyUI version: 0.12.0
ComfyUI frontend version: 1.37.11
Successfully installed py-cord[voice]
   🔧 torchaudio.save/load globally patched (scipy for WAV files, no TorchCodec)
   🔇 Suppressed torchaudio 2.9 migration warnings
APEX FusedRMSNorm is available and will be used for optimization
ℹ Critical package versions: NumPy 1.26.4, Librosa 0.11.0, Numba 0.62.1, PyTorch 2.10.0.dev20260111+rocm7.2.0.gitdea53f5b, TorchAudio 2.10.0+rocm7.2.0.git3b0e7a6f, Transformers 4.57.3, Accelerate 1.6.0, SoundFile 0.13.1
❌ F5-TTS not available: No module named 'flash_attn.bert_padding'
======================================================================
🚀 TTS Audio Suite v4.19.11
Universal multi-engine TTS extension for ComfyUI
✅ TTS Audio Suite v4.19.11 loaded with 32 nodes:
```

**Provide your ERROR full log**
```
Exception in thread Thread-6 (prompt_worker):
Traceback (most recent call last):
  File "/home/USER/.conda/envs/comfyui/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/home/USER/.conda/envs/comfyui/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/home/USER/ROCm/Almalinux/ComfyUI/main.py", line 259, in prompt_worker
    e.execute(item[2], prompt_id, extra_data, item[4])
  File "/home/USER/ROCm/Almalinux/ComfyUI/execution.py", line 687, in execute
    asyncio.run(self.execute_async(prompt, prompt_id, extra_data, execute_outputs))
  File "/home/USER/.conda/envs/comfyui/lib/python3.12/site-packages/nest_asyncio.py", line 30, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/.conda/envs/comfyui/lib/python3.12/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/home/USER/.conda/envs/comfyui/lib/python3.12/asyncio/futures.py", line 202, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/home/USER/.conda/envs/comfyui/lib/python3.12/asyncio/tasks.py", line 314, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/home/USER/ROCm/Almalinux/ComfyUI/execution.py", line 761, in execute_async
    comfy.model_management.unload_all_models()
  File "/home/USER/ROCm/Almalinux/ComfyUI/comfy/model_management.py", line 1734, in unload_all_models
    free_memory(1e30, get_torch_device())
  File "/home/USER/ROCm/Almalinux/ComfyUI/comfy/model_management.py", line 630, in free_memory
    if current_loaded_models[i].model.is_dynamic() and for_dynamic:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/ROCm/Almalinux/ComfyUI/custom_nodes/tts_audio_suite/utils/models/comfyui_model_wrapper/base_wrapper.py", line 414, in __getattr__
    return getattr(self.model, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Qwen3TTSModel' object has no attribute 'is_dynamic'
```

**Screenshots**
<img width="874" height="919" alt="Image" src="https://github.com/user-attachments/assets/50e88f75-11a4-478f-be40-9538e71c8f44" />

**System information**
 - OS: Linux
 - ComfyUI type: conda
 - Python version: 3.12

**Comment by diodiogod** [comment]
Hi @wasd-tech,

Thanks for reporting this! You're correct — this is a ComfyUI 0.12.0+ compatibility issue.

### Root Cause
ComfyUI 0.12.0 introduced a new `is_dynamic()` method call in their model management system (`model_management.py`). This method is called on all loaded models when freeing memory or loading models to GPU. Our model wrapper was forwarding this call to the underlying TTS model, which doesn't have this method — causing the `AttributeError`.

### The Fix
I've added the `is_dynamic()` method to our `ComfyUIModelWrapper` class. This fix:
- ✅ **Works on ComfyUI 0.12.0+** — the method now exists and returns `False` (TTS models have fixed memory requirements)
- ✅ **Backward compatible with ComfyUI 0.11.x** — the method exists but is never called on older versions
- ✅ **Protects all TTS engines** — not just Qwen3-TTS, but ChatterBox, F5-TTS, Higgs Audio, VibeVoice, CosyVoice, Step Audio EditX, and all others

### Update
Please update to **v4.20.4** to get this fix. You can update via ComfyUI-Manager or by pulling the latest from this repository.

Let me know if you still encounter any issues after updating!

**Comment by Vmars666** [comment]
I had  the same error , and the update didn't fix it, it just changed it to : 


> !!! Exception during processing !!! 'ChatterboxVC' object has no attribute 'partially_unload_ram'
> Traceback (most recent call last):
>   File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 527, in execute
>     output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
>                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 331, in get_output_data
>     return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 305, in _async_map_node_over_list
>     await process_inputs(input_dict, i)
>   File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 293, in process_inputs
>     result = f(**inputs)
>   File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy_api\internal\__init__.py", line 149, in wrapped_func
>     return method(locked_class, **inputs)
>   File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy_api\latest\_io.py", line 1667, in EXECUTE_NORMALIZED
>     to_return = cls.execute(*args, **kwargs)
>   File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_custom_sampler.py", line 767, in execute
>     samples = comfy.sample.sample_custom(model, noise, cfg, sampler, sigmas, positive, negative, latent_image, noise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=noise_seed)
>   File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\sample.py", line 71, in sample_custom
>     samples = comfy.samplers.sample(model, noise, positive, negative, cfg, model.load_device, sampler, sigmas, model_options=model.model_options, latent_image=latent_image, denoise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
>   File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 1067, in sample
>     return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
>            ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 1049, in sample
>     output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed, latent_shapes=latent_shapes)
>   File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\patcher_extension.py", line 112, in execute
>     return self.original(*args, **kwargs)
>            ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 983, in outer_sample
>     self.inner_model, self.conds, self.loaded_models = comfy.sampler_helpers.prepare_sampling(self.model_patcher, noise.shape, self.conds, self.model_options)
>                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\sampler_helpers.py", line 130, in prepare_sampling
>     return executor.execute(model, noise_shape, conds, model_options=model_options, force_full_load=force_full_load)
>            ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\patcher_extension.py", line 112, in execute
>     return self.original(*args, **kwargs)
>            ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\sampler_helpers.py", line 138, in _prepare_sampling
>     comfy.model_management.load_models_gpu([model] + models, memory_required=memory_required + inference_memory, minimum_memory_required=minimum_memory_required + inference_memory, force_full_load=force_full_load)
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 767, in load_models_gpu
>     load_models_gpu_orig(models, memory_required=memory_required, force_patch_weights=force_patch_weights,
>     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>                          minimum_memory_required=minimum_memory_required, force_full_load=force_full_load)
>                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 716, in load_models_gpu_orig
>     free_memory(total_memory_required[device] * 1.1 + extra_mem, device, for_dynamic=free_for_dynamic, ram_required=total_ram_required[device])
>     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 640, in free_memory
>     current_loaded_models[i].model.partially_unload_ram(ram_to_free)
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\TTS-Audio-Suite\utils\models\comfyui_model_wrapper\base_wrapper.py", line 430, in __getattr__
>     return getattr(self.model, name)
> AttributeError: 'ChatterboxVC' object has no attribute 'partially_unload_ram'

**Comment by wasd-tech** [comment]
@diodiogod now I have `AttributeError: 'Qwen3TTSModel' object has no attribute 'partially_unload_ram'`.

**Comment by MMaximuss** [comment]
I am experiencing almost the same error: `AttributeError: 'ChatterboxOfficial23LangTTS' object has no attribute 'partially_unload_ram'`

Output from 'grep -RIn "partially_unload_ram"' in ComfyUI folder (latest release: v0.12.3):
```
comfy/model_patcher.py:1014:    def partially_unload_ram(self, ram_to_unload):
comfy/model_patcher.py:1463:        self.partially_unload_ram(1e32)
comfy/model_patcher.py:1579:    def partially_unload_ram(self, ram_to_unload):
comfy/model_patcher.py:1599:            self.partially_unload_ram(1e32)
comfy/model_management.py:640:            current_loaded_models[i].model.partially_unload_ram(ram_to_free)
```
